apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: rhf
  labels: { app: filebeat }
spec:
  selector:
    matchLabels: { app: filebeat }
  template:
    metadata:
      labels: { app: filebeat }
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.15.0
          args: ["-c", "/etc/filebeat.yml", "-e"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: applogs
              mountPath: /app/logs
      volumes:
        - name: config
          configMap:
            name: filebeat-config
        - name: applogs
          hostPath:
            path: /tmp/rider-logs
