apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: rhf
data:
  logstash.conf: |
    input { beats { port => 5044 } }
    filter { json { source => "message" } }
    output {
      elasticsearch { hosts => ["http://elasticsearch:9200"] index => "rider-logs-%{+YYYY.MM.dd}" }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: rhf
  labels: { app: logstash }
spec:
  selector:
    matchLabels: { app: logstash }
  template:
    metadata:
      labels: { app: logstash }
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.0
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: rhf
spec:
  selector: { app: logstash }
  ports:
    - port: 5044
      targetPort: 5044
