spring:
  datasource:
    url: jdbc:postgresql://rider-db:5434/riderdb
    username: rider
    password: riderpw

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
