apiVersion: v1
kind: PersistentVolume
metadata:
  name: rider-db-pv
  namespace: rhf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/rider-db
