global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'rider-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rider-service:9081']

