apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-db
  namespace: rhf
  labels:
    app: rider-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-db
  template:
    metadata:
      labels:
        app: rider-db
    spec:
      containers:
        - name: rider-db
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: riderdb
            - name: POSTGRES_USER
              value: rider
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rider-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 5434
          volumeMounts:
            - name: rider-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: rider-db-storage
          persistentVolumeClaim:
            claimName: rider-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rider-db
  namespace: rhf
spec:
  type: ClusterIP
  selector:
    app: rider-db
  ports:
    - port: 5434
      targetPort: 5434
