apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: rhf
  labels:
    app: rider-service
spec:
  type: NodePort
  selector:
    app: rider-service
  ports:
    - name: http
      port: 9081
      targetPort: 9081
      nodePort: 30081
